export const GET_SPACES = "GET_SPACES"
export const GET_PAGES = "GET_PAGES"
export const IS_LOGIN = "IS_LOGIN"
export const IS_NOT_LOGIN = "IS_NOT_LOGIN"
export const CLEAN_PAGES = "CLEAN_PAGES"
export const TREE_PAGES = "TREE_PAGES"
export const SPACE_NAME = "SPACE_NAME"
export const OPEN_SPACE = "OPEN_SPACE"